# Generated by Django 4.1.4 on 2023-01-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Стоимость заказа'),
        ),
    ]
